services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_DIRECTORY}:/config
      - ${DOWNLOADS_DIRECTORY}:/downloads #optional
      - ${INCOMPLETE_DOWNLOADS_DIRECTORY}:/incomplete-downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped

networks:
  internal:
    external:
      name: internal_network
