services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    restart: unless-stopped
    networks:
      - internal
    devices:
      - /dev/dri:/dev/dri # GPU Support
    env_file:
      - .env
    volumes:
      - ${CONFIG_DIRECTORY}:/config
      - ${TV_LIBRARY}:/library/tv
      - ${MOVIE_LIBRARY}:/library/movies
      - ${CACHE_DIRECTORY}:/tmp/unmanic
    ports:
      - 8888:8888

networks:
  internal:
    external:
      name: internal_network
